In [1]:
import numpy as np
import pandas as pd
import h5py

In [2]:
crs = np.loadtxt('samplenamecross.txt',dtype='str').astype(int)

In [3]:
ver = np.loadtxt('samplenamevertical.txt',dtype='str').astype(int)
small = np.loadtxt('samplenamesmall.txt',dtype='str').astype(int)

In [4]:
crs

array([5070, 5071, 5072, ..., 6056, 6073, 6192])

In [5]:
from scipy.stats.stats import pearsonr

In [131]:
std = pd.read_excel('Desktop/emaize/backtoresults/9.11/9.8.csv')

In [132]:
trait1 = np.asarray(std['trait1'])
trait2 = np.asarray(std['trait2'])
trait3 = np.asarray(std['trait3'])

In [8]:
test = pd.read_excel('Desktop/emaize/backtoresults/9.11/fastlmm.xlsx')
test1 = pd.read_excel('Desktop/emaize/backtoresults/9.11/fastlmm1.xlsx')
test2 = pd.read_excel('Desktop/emaize/backtoresults/9.11/fastlmm2.xlsx')
test3 = pd.read_excel('Desktop/emaize/backtoresults/9.11/fastlmm3.xlsx')
test4 = pd.read_excel('Desktop/emaize/backtoresults/9.11/fastlmm4.xlsx')
test5 = pd.read_excel('Desktop/emaize/backtoresults/9.11/fastlmm5.xlsx')

In [9]:
pearsonr(trait1,np.asarray(test4['trait1']))

(0.85499986316363485, 0.0)

In [10]:
pearsonr(trait2,np.asarray(test4['trait2']))

(0.67795276554092143, 1.4502027468011429e-196)

In [127]:
xgb = pd.read_csv('9.11xgboost.csv')

In [12]:
line = pd.read_csv('9.11linear.csv')

In [13]:
x = np.asarray(xgb['Unnamed: 0'])
print(np.__version__)

1.13.1


In [24]:
np.isin(xgb['Unnamed: 0'],crs)

array([False, False, False, ..., False, False, False], dtype=bool)

In [25]:
np.isin(xgb['Unnamed: 0'],ver)

array([False, False, False, ...,  True,  True,  True], dtype=bool)

In [128]:
xbgr_ver = xgb.iloc[np.isin(xgb['Unnamed: 0'],ver)]

In [30]:
xbgr_crs = xgb.iloc[np.isin(xgb['Unnamed: 0'],crs)]

In [31]:
line_small = line.iloc[np.isin(line['Unnamed: 0'],small)]

In [38]:
line_small['trait3.2']

342     0.469561
357     1.030860
434     1.125911
439     1.819917
456     0.886761
554     0.216978
569     0.466984
646     0.261198
651     0.770720
668     0.438353
781     0.873135
796     0.988322
873     1.311420
878     1.780257
895     1.020542
1038    0.982509
1053    0.647519
1130    0.879077
1135    1.353525
1152    1.350853
1260    0.461293
1275    1.329129
1352    1.285208
1357    1.557732
1374    1.329246
Name: trait3.2, dtype: float64

In [149]:
xgb.loc[line_small['trait3.2'].index, 'trait3'] = line_small['trait3.2']

In [150]:
trait3_final = xgb['trait3']

In [119]:
lmm = pd.read_excel('9.8.xlsx')

In [151]:
lmm.loc[xbgr_ver['trait2'].index, 'trait2'] = xbgr_ver['trait2']
trait2_final = lmm['trait2']

In [67]:
pearsonr(np.asarray(xgbtrait3['trait3']),trait3_final)

(0.95144475306872123, 0.0)

In [124]:
pearsonr(trait2,trait2_final)

(0.94728865350547042, 0.0)

In [64]:
xgbtrait3 = pd.read_csv('1.csv')

In [66]:
np.asarray(xgbtrait3['trait3'])

array([-1.33597481, -1.45568335, -1.49988902, ...,  0.34795436,
        0.79883134,  0.06329593])

In [152]:
lmm.loc[xbgr_ver['trait1'].index, 'trait1'] = xbgr_ver['trait1']
trait1_final = lmm['trait1']

In [153]:
x = np.random.normal(0, 0.01, 1456)

In [154]:
y = np.random.normal(0, 0.01, 1456)
z = np.random.normal(0, 0.01, 1456)

In [155]:
trait2_final = trait2_final + x

In [156]:
trait3_final = trait3_final + y

In [157]:
trait1_final = trait1_final + z

In [158]:
whole = np.vstack((trait1_final,trait2_final,trait3_final))

In [159]:
whole =  whole.T

In [160]:
whole

array([[-1.92128834, -0.46494556, -1.40823047],
       [-1.92258381, -0.17518244, -1.21527564],
       [-1.56532429, -0.22610685, -1.45205061],
       ..., 
       [-0.42286536, -1.70042307,  0.45905679],
       [-0.36060818, -1.40509686,  0.73305266],
       [-0.64171091, -1.77313623,  0.04694033]])

In [161]:
predictions = pd.DataFrame(data=whole )
predictions.columns = ['trait1', 'trait2', 'trait3']
b = np.arange(4754,6210)
predictions = predictions.set_index([b])
predictions.to_csv('9.11final.csv')

In [162]:
ttt = pd.read_csv('9.11final.csv')

In [163]:
np.asarray(ttt['trait1'])

array([-1.92128834, -1.92258381, -1.56532429, ..., -0.42286536,
       -0.36060818, -0.64171091])

In [164]:
pearsonr(np.asarray(xgbtrait3['trait3']),np.asarray(ttt['trait3']))

(0.95151777176101016, 0.0)

In [165]:
pearsonr(np.asarray(lmm['trait2']),ttt['trait2'])

(0.99994433388427684, 0.0)